### ISSUE TITLE
Not compiling sass issue after Mac OS 10.13 update.

### ISSUE THREAD

**Issue by grafxflow** [oklai/koala#694] opened 2017-10-27 15:46 UTC
koala Version 2.2.0

Mac OS 10.13

It doesn't seem to compile and is giving the following error. Only started after updating Mac OS.

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'sass' (>= 0) among 15 total gem(s) (Gem::LoadError)

**Comment by zaygraveyard** [comment] 2017-11-16 09:10
Duplicate of #679

**Closed by zaygraveyard** 2017-11-16 09:10 UTC
