### ISSUE TITLE
Koala 2.1.0 error

### ISSUE THREAD

**Issue by rodenacker** [oklai/koala#582] opened 2017-04-26 11:31 UTC
I just upgraded to the new Koala 2.1.0 and get the message below when compiling my scss files. Looks like I will have to revert back to Scout... 

![image](https://cloud.githubusercontent.com/assets/2085324/25430837/83fe3462-2a7e-11e7-891d-13343c8e55eb.png)

Franz

**Comment by zaygraveyard** [comment] 2017-04-26 11:35
Duplicate of #579

**Closed by zaygraveyard** 2017-04-26 11:35 UTC

**Comment by rodenacker** [comment] 2017-04-26 11:37
Thanks. When do you expect to have this fixed?
Franz

**Comment by zaygraveyard** [comment] 2017-04-26 13:44
I'm working on it, so hopefully before tonight
