### ISSUE TITLE
在安装时安装目录下的全部文件被删掉

### ISSUE THREAD

**Issue by niuyi1017** [oklai/koala#701] opened 2017-11-17 10:20 UTC
**Koala version**
2.2.0 2017-05-02
**Bug report or feature request?**
您好，我在koala网站上下载了koala，但在安装时安装目录下的全部文件都被koala删掉了
下载地址https://github.com/oklai/koala/releases/download/v2.2.0/KoalaSetup.exe
之前同样安装在此目录的程序全都不能用了

**Comment by zaygraveyard** [comment] 2017-11-17 10:54
Duplicate of #638
Sorry about that, but the next release (should be coming this weekend) will warn before deleting the files.

**Closed by zaygraveyard** 2017-11-17 10:54 UTC
