### ISSUE TITLE
koala does not open in ubuntu 14.04

### ISSUE THREAD

**Issue by mehedi-sharif** [oklai/koala#296] opened 2014-09-20 22:44 UTC
I have installed koala in my ubuntu 14.04 many time but it is not opened.I have tried it many times.even I set up ubuntu 2times for using koala.please help me.
Thanks

**Comment by RonyKader** [comment] 2015-01-20 09:32
Step one : Download Udev library from this page -> https://www.dropbox.com/sh/pwze4wlsfmn90ee/AABMLIuNlDU5a_KwUkoPUOnNa?dl=0 libudev0_i386 for Ubuntu libudev0_amd64, if you are using Ubuntu 64bit.
Step Two : Launch the .deb package that you have just downloaded. Now  Open with Ubuntu Software Centre or Double  Click .
Step Three : Now Open your Terminal and write 
1 -> cd /usr/lib64
2 -> cd /usr/libudev0_175-0ubuntu19_amd64.deb
3 -> sudo ln -s libudev.so.1 libudev.so.0

Step Four : Now Just go to your Search Option and write Kola then you Find Koala Icon .Now Just Launch it and Enjoy with Koala ..

For Details Just go to https://gist.github.com/RonyKader/1c359f36436a6fd47dca

**Comment by QORTEC** [comment] 2015-07-10 08:42
Dupe of #246

**Closed** 2015-07-10 08:44 UTC
