### ISSUE TITLE
OSX notifications & delete project

### ISSUE THREAD

**Issue by Rvdv87** [oklai/koala#447] opened 2015-08-19 06:40 UTC
First of all, i love this app! :+1: 

When i have Koala minimized and the notifications popup, the notifications become the active app. So when you quickly press some keys, koala popups up because the keys get pressed in Koala. Is it possible to use the OSX notifications? 

Then, a second (small) problem that happens because the app get's active when a notification popups up. When you quickly press backspace, the active project in Koala will be deleted without any notification.

**Comment by combs** [comment] 2015-09-04 16:26
agree on the notifications--my editor autosaves often and each time, Koala steals focus because of a syntax error (well, yeah, I am halfway done with the line...)

**Comment by zaygraveyard** [comment] 2017-05-17 08:01
Fixed in v2.2.0
Also duplicate of #621
Ref #384 for native notifications

**Closed by zaygraveyard** 2017-05-17 08:01 UTC
