### ISSUE TITLE
How to solve this software startup error?

### ISSUE THREAD

**Issue by cooper1x** [oklai/koala#687] opened 2017-10-16 02:21 UTC
**Koala version**
v2.2.0
**Bug report or feature request?**
![image](https://user-images.githubusercontent.com/9080789/31592545-ba12fbf4-b25b-11e7-8927-5895035ae890.png)

**Comment by zaygraveyard** [comment] 2017-10-16 04:58
Duplicate of #639

**Closed by zaygraveyard** 2017-10-16 04:58 UTC
