### ISSUE TITLE
Problems windows 10 

### ISSUE THREAD

**Issue by alenet1992** [oklai/koala#581] opened 2017-04-26 09:40 UTC
I updated to the new version, unfortunately had to return the old version because the new version. Can not find a toolbar variable, and the variable does not exist in any sass file
Continuation of a good work.

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at createNotifierWindow (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\notifier.js:131:22)
    at showNotification (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\notifier.js:75:18)
    at Object.exports.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\notifier.js:24:5)
    at SassCompiler.Compiler.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\Compiler.js:67:11)
    at C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\compilers\SassCompiler.js:153:18
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at createNotifierWindow (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\notifier.js:131:22)
    at showNotification (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\notifier.js:75:18)
    at Object.exports.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\notifier.js:24:5)
    at SassCompiler.Compiler.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\Compiler.js:67:11)
    at C:\Users\UTILIZ~1\AppData\Local\Temp\nw1624_26526\app\scripts\compilers\SassCompiler.js:153:18
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at createNotifierWindow (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\notifier.js:131:22)
    at showNotification (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\notifier.js:75:18)
    at Object.exports.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\notifier.js:24:5)
    at SassCompiler.Compiler.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\Compiler.js:67:11)
    at C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\compilers\SassCompiler.js:153:18
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at createNotifierWindow (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\notifier.js:131:22)
    at showNotification (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\notifier.js:75:18)
    at Object.exports.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\notifier.js:24:5)
    at SassCompiler.Compiler.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\Compiler.js:67:11)
    at C:\Users\UTILIZ~1\AppData\Local\Temp\nw7592_8473\app\scripts\compilers\SassCompiler.js:153:18
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at createNotifierWindow (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\notifier.js:131:22)
    at showNotification (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\notifier.js:75:18)
    at Object.exports.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\notifier.js:24:5)
    at SassCompiler.Compiler.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\Compiler.js:67:11)
    at C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\compilers\SassCompiler.js:153:18
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at createNotifierWindow (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\notifier.js:131:22)
    at showNotification (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\notifier.js:75:18)
    at Object.exports.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\notifier.js:24:5)
    at SassCompiler.Compiler.throwError (C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\Compiler.js:67:11)
    at C:\Users\UTILIZ~1\AppData\Local\Temp\nw3008_10881\app\scripts\compilers\SassCompiler.js:153:18
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)

---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)

**Comment by intared** [comment] 2017-04-26 10:14
I am having the same issue.

Turning off autoprefix allows compilation in my case.

That's ok for dev, but it'd be cool to get this back for production use.

**Comment by zaygraveyard** [comment] 2017-04-26 11:20
Duplicate of #579

**Closed by zaygraveyard** 2017-04-26 11:20 UTC
