### ISSUE TITLE
Error when attempting to save SCSS file in Visual Studio

### ISSUE THREAD

**Issue by BRichardson2993** [oklai/koala#590] opened 2017-04-26 18:29 UTC
![koalaerror](https://cloud.githubusercontent.com/assets/13844631/25450358/4a90def4-2a84-11e7-8f9e-79b717e5fbb8.PNG)

This worked flawlessly prior to the recent update.

**Comment by zaygraveyard** [comment] 2017-04-26 21:39
Duplicate of #579

**Closed by zaygraveyard** 2017-04-26 21:39 UTC
