### ISSUE TITLE
App should notify without coming to the front.

### ISSUE THREAD

**Issue by jenniferaslan** [oklai/koala#542] opened 2016-09-20 21:01 UTC
Every time the app notifies me that it’s been successful with a compilation, it comes to the front (becomes the focused application). Will you please make it so that it remains hidden, but still displays the notification, perhaps using the notification system built into El Capitan? I’m using the Mac version on OS X 10.11.6. It drives me crazy that I have to minimize or click back to the app I was in, every time I receive a Koala notification. Thanks.

**Comment by onepartscissors** [comment] 2016-11-24 06:53
+1 on this, yes please!

I love this app! Been using Scout and happy to be rid of that Adobe Air app, this is cool and has minify in there too! 💯 💯 💯

**Comment by zaygraveyard** [comment] 2017-05-17 07:31
Fixed in v2.2.0
Also duplicate of #621
Ref #384 for native notifications

**Comment by onepartscissors** [comment] 2017-05-17 07:32
I saw this is fixed in the newest version! So cool! Thanks Guys! 🚀 🚀 🚀

**Closed by zaygraveyard** 2017-05-17 07:31 UTC
Labels: feature, macos

**Comment by onepartscissors** [comment] 2017-05-17 07:35
a funny story about this... i got into such a habit of editing my files in Sublime, Cmd+S, Koala comes to the front, Cmd-Tab twice to browser, and refresh.

So when this one was fixed, i would Cmd+s my file, Cmd-Tab twice to... what, what app is this now, mail? what?
And it took me about an hour to realize, hold on, Koala isn't coming to the front any more, i don't need to Cmd-Tab after saving. It had become a mental tick! :)
