### ISSUE TITLE
Koala crash

### ISSUE THREAD

**Issue by ScanThemes** [oklai/koala#762] opened 2018-07-04 14:59 UTC
**2.3.0**

**Bug report**

The program stopped working. At startup gives an error:
![0180704175218](https://user-images.githubusercontent.com/24419426/42284009-dcadf27e-7fb3-11e8-86c0-211568aff269.jpeg)
![80704175310](https://user-images.githubusercontent.com/24419426/42284025-e7e9c622-7fb3-11e8-877a-e2b39f0841f8.jpeg)
Reinstallation does not help.

Thank you.

**Comment by zaygraveyard** [comment] 2018-07-04 15:13
Duplicate of #740?
You can try deleting `%USERPROFILE%/.koala/settings.json`

**Comment by zaygraveyard** [comment] 2018-07-04 16:09
I'm glad it helped :smile:

**Closed by zaygraveyard** 2018-07-04 16:09 UTC

**Comment by 5572189** [comment] 2019-03-26 07:27
Why didn't mine, and koala just got stuck
