### ISSUE TITLE
windows安装koala后，打开koala出现 compiler CSS(SASS LESS JS)  error

### ISSUE THREAD

**Issue by dachuiwu** [oklai/koala#730] opened 2018-01-28 14:00 UTC
**Koala version**
2.3.0

**Bug report or feature request?**
 no

![Uploading QQ截图20180128215606.png…]()
![Uploading QQ截图20180128215611.png…]()
![Uploading QQ截图20180128215616.png…]()

**Comment by dachuiwu** [comment] 2018-01-28 14:01
![qq 20180128215606](https://user-images.githubusercontent.com/22026651/35482936-afdd1256-0476-11e8-87ce-c1e5c056c38c.png)
![qq 20180128215611](https://user-images.githubusercontent.com/22026651/35482938-b50291ac-0476-11e8-97a2-b6eb44cc139d.png)
![qq 20180128215616](https://user-images.githubusercontent.com/22026651/35482942-b8630f3e-0476-11e8-9c71-41968c30d8ff.png)
![qq 20180128215545](https://user-images.githubusercontent.com/22026651/35482943-bb94e100-0476-11e8-852b-2f00383d1290.png)
![qq 20180128215552](https://user-images.githubusercontent.com/22026651/35482944-bdf89054-0476-11e8-8865-b3de882316ca.png)

**Comment by zaygraveyard** [comment] 2018-01-29 09:26
Duplicate of #726

**Closed by zaygraveyard** 2018-01-29 09:26 UTC
