### ISSUE TITLE
System cannot find file at given path

### ISSUE THREAD

**Issue by EEKimS** [oklai/koala#600] opened 2017-04-28 14:19 UTC
After updating to version 2.1.1, suddenly my koala is unable to locate any file from any directory, while it was able to get just 5 minutes before.

Koala also takes a lot longer to start, but the error with the files has rendered it unusable.
![koala-error](https://cloud.githubusercontent.com/assets/7404404/25532639/3c80983c-2beb-11e7-83ec-9be88ecd1574.png)

I get this error on every single project, even newly created ones. Please help!

I have checked all of the folder permissions and everything, the koala update is the only thing that has changed

EDIT:

Windows 10, Xampp, each site has it's own folder and everywhere the Sass needs to be has it's own config.

I downgraded to version 2.0.4 and this issue no longer happens, if that helps.

**Comment by MatteoPieroni** [comment] 2017-04-28 15:19
Same here!

Windows 10, using xampp with folder C:/htdocs

**Comment by edudix** [comment] 2017-04-28 16:29
same here

**Comment by xMrKrisx** [comment] 2017-04-28 17:51
same problem. Bright side, the error message of v 2.1.0 is fixed.

**Comment by zaygraveyard** [comment] 2017-04-28 18:14
Duplicate of #598
Looking into it

**Closed by zaygraveyard** 2017-04-28 18:14 UTC
