### ISSUE TITLE
compile error after updating to 2.1.1

### ISSUE THREAD

**Issue by itacode** [oklai/koala#603] opened 2017-04-29 02:48 UTC
Thank you.
I cannot compile scss files anymore. I get the following error with mojibake.
I am on Japanese windows 10 version 1703 build 15063.138.
I felt as the installation went wrong because the Koala folder in program files (C:\Program Files (x86)\Koala) contains some files but only one folder called locales.
![koala-error](https://cloud.githubusercontent.com/assets/9909272/25552286/7c522134-2cd0-11e7-827b-dc4f4b4e687a.png)

**Comment by errand** [comment] 2017-04-29 14:49
Hey Guys!
Same here!

**Comment by zaygraveyard** [comment] 2017-04-29 15:15
Thank you for the info.
Duplicate of #598

**Closed by zaygraveyard** 2017-04-29 15:15 UTC
