### ISSUE TITLE
Koala gives errorcode 0xc000007b in version 2.20

### ISSUE THREAD

**Issue by BeRambo** [oklai/koala#631] opened 2017-05-16 17:04 UTC
My version 2.14 stopped working so I thought I'd give 2.20 a shot. When running Koala, it's giving me error 0xc000007b. 

I've installed it on 2 computers, both running Windows 10 64-bit. It gives the same error on both devices.

![image](https://cloud.githubusercontent.com/assets/28736920/26118485/69609a0e-3a6a-11e7-859e-b7b4ae2715ba.png)

!Update: version 2.14 is working for me at the moment.!

**Comment by nemrac99** [comment] 2017-05-16 19:28
Same issue - running Win10 64bit

**Comment by brussens** [comment] 2017-05-16 21:05
I have the same error. Windows 10 x64.

**Comment by zaygraveyard** [comment] 2017-05-16 21:11
Duplicate of #630

**Closed by zaygraveyard** 2017-05-16 21:11 UTC
