### ISSUE TITLE
Koala don't compile sass with Mac High Sierra

### ISSUE THREAD

**Issue by amapizen** [oklai/koala#699] opened 2017-11-05 23:09 UTC
**Koala version**

**Bug report or feature request?**

**Comment by paulcheney** [comment] 2017-11-13 23:46
Same problem, seems to be a problem related to Ruby Framework.
Any plans to correct this problem?

**Comment by amapizen** [comment] 2017-11-14 00:27
I use Gulp or Grunt to compile in High Sierra, that's why i don't recommend to use graphic compilers.

**Comment by paulcheney** [comment] 2017-11-14 21:28
I found "Scout-App" that works great in High Sierra until Koala get updates.

**Comment by amapizen** [comment] 2017-11-14 21:44
Yeah but use Graphic Compilers like GhostLab CodeKit etc doesn't help, future is to use task managers ej Gulp. Scout is for newbies

**Comment by zaygraveyard** [comment] 2017-11-16 09:10
Duplicate of #679

**Closed by zaygraveyard** 2017-11-16 09:10 UTC
