### ISSUE TITLE
notifier.js and compiler error

### ISSUE THREAD

**Issue by costellos2010** [oklai/koala#632] opened 2017-05-16 17:48 UTC
**Koala version: 2.1.0 Because of 0xc000007b error**

**Bug report**

I'm getting this error(see screenshot) when I run the compiler. I can upgrade to 2.2.0 because of the 0xc000007b error. I need this to work its the only compiler I use/know of that can do JS and Sass in the same project with out me having to pay for it. 

![untitled-1](https://cloud.githubusercontent.com/assets/8794701/26120328/4e0e6b36-3a3e-11e7-97bc-6332e3759f0d.jpg)

**Comment by zaygraveyard** [comment] 2017-05-16 21:12
Duplicate of #630

**Closed by zaygraveyard** 2017-05-16 21:12 UTC
