### ISSUE TITLE
Koala uncaughtException

### ISSUE THREAD

**Issue by zmoe84** [oklai/koala#614] opened 2017-05-04 15:27 UTC
TypeError: Cannot read property 'length' of undefined at C:\Program Files(x86)\Koala\app\scripts\compilers\CssCompile.js: 64:67
at FSReqWrap.oncomplete (fs.js:114:15)

How to solve it?
Re-Install and .koala folder delete doesn´t work.

**Comment by zaygraveyard** [comment] 2017-05-04 16:36
Duplicate of #611

**Closed by zaygraveyard** 2017-05-04 16:36 UTC
