### ISSUE TITLE
uncaughtException

### ISSUE THREAD

**Issue by bautistaI** [oklai/koala#672] opened 2017-09-08 15:24 UTC
**Koala version**

**Bug report or feature request?**

Getting this error while Koala is running. Even when not actually compiling any files.

---uncaughtException---
RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at compile (/Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:259:17)
    at /Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:273:13
    at Array.forEach (native)
    at compile (/Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:259:17)
    at /Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:273:13
    at Array.forEach (native)
    at compile (/Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:259:17)
    at /Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:273:13
    at Array.forEach (native)

**Comment by zaygraveyard** [comment] 2017-10-10 08:48
Duplicate of #681

**Closed by zaygraveyard** 2017-10-10 08:48 UTC
