### ISSUE TITLE
Since latest update SASS files don't compile anymore 

### ISSUE THREAD

**Issue by phlpedr** [oklai/koala#583] opened 2017-04-26 11:56 UTC
Hello, since the latest update my SASS files don't compile anymore. There's always an error (please find attached image). Is this a general Koala problem or a local one?
Best regards, Philipp

![2017-04-26 13_48_25-_koala](https://cloud.githubusercontent.com/assets/11057193/25433158/c10bddba-2a87-11e7-869b-60435e10df9b.png)
)

**Comment by pb-86** [comment] 2017-04-26 12:01
I have the exactly same issue with lastest version.

**Comment by srijaydeathwish** [comment] 2017-04-26 12:46
Same issue. Happening after 2.1.0 update.

**Comment by zaygraveyard** [comment] 2017-04-26 13:42
Duplicate of #579

**Closed by zaygraveyard** 2017-04-26 13:42 UTC
