### ISSUE TITLE
Ver 2.1.0 cannot be opened on Mac

### ISSUE THREAD

**Issue by bbrandtlv** [oklai/koala#587] opened 2017-04-26 16:30 UTC
Hey, just updated to new version (2.1.0) and app cannot be opened.
Deleted and tried again, downloaded again... nothing.
Got back to 2.0.4

**Comment by miqalarcia** [comment] 2017-04-26 16:44
Same for me!

**Comment by aargenis** [comment] 2017-04-26 16:56
Same for me

**Comment by puntomaturana** [comment] 2017-04-26 17:48
Same for me

**Comment by zaygraveyard** [comment] 2017-04-26 21:40
Is it the same as #580?

**Comment by codesquatch** [comment] 2017-04-27 00:20
Same

**Comment by KingKarrow** [comment] 2017-04-27 17:59
@zaygraveyard Yep. I'm seeing it too.

**Comment by zaygraveyard** [comment] 2017-04-27 19:35
Duplicate of #580

**Closed by zaygraveyard** 2017-04-27 19:35 UTC
