### ISSUE TITLE
after eval() code removed incorrect

### ISSUE THREAD

**Issue by hxlzq** [oklai/koala#664] opened 2017-07-13 09:37 UTC
Koala 2.2.0

if (HXWebDynamicPage != null && HXWebDynamicPage._Internal != null)
 {
      eval("fnEventHandlerFunc = HXWebDynamicPage._Internal._OnHXPage" + strFuncBaseName);
            if (fnEventHandlerFunc != null)
                fnEventHandlerFunc(arrHanlderCode.slice(1).join("."), evt);
 }

compiled code (incorrect):
null != HXWebDynamicPage && null != HXWebDynamicPage._Internal && (eval("fnEventHandlerFunc = HXWebDynamicPage._Internal._OnHXPage" + strEventHandlerFuncBaseName);

correct compiled code in Version 2.0.4:

null != HXWebDynamicPage && null != HXWebDynamicPage._Internal && (eval("fnEventHandlerFunc = HXWebDynamicPage._Internal._OnHXPage" + strEventHandlerFuncBaseName), null != fnEventHandlerFunc && fnEventHandlerFunc(arrHanlderCode.slice(1).join("."), evt));

**Comment by zaygraveyard** [comment] 2017-07-14 15:00
Thanks for reporting this.
But, unfortunately, I was unable to reproduce it!

BTW `eval` is evil and you shouldn't use it unless absolutely necessary, and in your case it isn't:
```js
if (HXWebDynamicPage != null && HXWebDynamicPage._Internal != null)
{
  fnEventHandlerFunc = HXWebDynamicPage._Internal['_OnHXPage' + strFuncBaseName];
  if (fnEventHandlerFunc != null) {
    fnEventHandlerFunc(arrHanlderCode.slice(1).join("."), evt);
  }
}
```

**Comment by zaygraveyard** [comment] 2017-10-10 08:50
Closing since I can't reproduce it and it's probably related to uglify-js

**Closed by zaygraveyard** 2017-10-10 08:50 UTC
