### ISSUE TITLE
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.

### ISSUE THREAD

**Issue by Bubelbub** [oklai/koala#593] opened 2017-04-27 10:30 UTC
Hey guys,

I installed Koala a few minutes ago and tried to compile my scss styles.
But then I got this error.

	---uncaughtException---
	Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
		at validate (extensions::schemaUtils:34:13)
		at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:116:3)
		at Object.<anonymous> (extensions::binding:414:30)
		at createNotifierWindow (C:\Users\Bubelbub\AppData\Local\Temp\nw2124_2251\app\scripts\notifier.js:131:22)
		at showNotification (C:\Users\Bubelbub\AppData\Local\Temp\nw2124_2251\app\scripts\notifier.js:75:18)
		at Object.exports.throwError (C:\Users\Bubelbub\AppData\Local\Temp\nw2124_2251\app\scripts\notifier.js:24:5)
		at SassCompiler.Compiler.throwError (C:\Users\Bubelbub\AppData\Local\Temp\nw2124_2251\app\scripts\Compiler.js:67:11)
		at C:\Users\Bubelbub\AppData\Local\Temp\nw2124_2251\app\scripts\compilers\SassCompiler.js:232:18
		at ChildProcess.exithandler (child_process.js:212:5)
		at emitTwo (events.js:106:13)

Maybe there is a problem with the `SassCompiler.js`? But If I specify the sass compiler by myself then it's not working, too.

    gem install sass
    sass -v
    Sass 3.4.23 (Selective Steve)

![2017-04-27 12_29_21-koala - a cool tool for web developers](https://cloud.githubusercontent.com/assets/319352/25479442/2c424976-2b45-11e7-9b9a-0cfe221cf989.png)

**Comment by SummerChroma** [comment] 2017-04-27 16:12
I am having the same problem...

**Comment by zaygraveyard** [comment] 2017-04-27 17:14
Duplicate of #579

**Closed by zaygraveyard** 2017-04-27 17:14 UTC
