### ISSUE TITLE
Compiling Sass Not Working

### ISSUE THREAD

**Issue by remminator** [oklai/koala#594] opened 2017-04-27 17:11 UTC
I'm having some issues compiling SASS.

I keep getting errors.

[Screenshot](http://i.imgur.com/WmERAkg.png)

Thanks!

**Comment by zaygraveyard** [comment] 2017-04-27 17:15
Duplicate of #579

**Closed by zaygraveyard** 2017-04-27 17:15 UTC

**Comment by remminator** [comment] 2017-04-27 17:25
Thanks a ton!
