### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by alexsemy** [oklai/koala#604] opened 2017-04-30 09:47 UTC
Just updated my Koala app from 2.0.4 to 2.1.1 and now when i try to compele all my projects (SCSS files) I get the Error (in attached Screenshot).
But before, on 2.0.4 version of the App everything worked perfect!

I can`t understand the error message down right below. So... What is the problem?

Thanks!
![koala_error](https://cloud.githubusercontent.com/assets/28218743/25563332/27258664-2dbc-11e7-91b6-9faf83040daf.jpg)

**Comment by zaygraveyard** [comment] 2017-04-30 10:40
Duplicate of #598

**Closed by zaygraveyard** 2017-04-30 10:40 UTC
